data:
    data_root: ./data/
    data_format: csv
    train_data: ./data/criteo_x4/train_sample.csv
    valid_data: ./data/criteo_x4/valid_sample.csv
    test_data: ./data/criteo_x4/test_sample.csv
    min_categr_count: 2
    feature_cols:
        - { name: [ I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13 ],
            active: True, dtype: float, type: numeric, preprocess: convert_to_bucket, na_value: 0 }
        - { name: [ C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26 ],
            active: True, dtype: str, type: categorical, na_value: "" }
    label_col: { name: label, dtype: float }

model:
    model_root: './checkpoints/'
    log_root: './logs/'
    dataset_id: criteo_x4
    workers: 8
    verbose: 1
    patience: 2
    pickle_feature_encoder: True
    #use_hdf5: True
    #save_best_only: True
    #every_x_epochs: 1
    debug: False
    model: WDLEstimator
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    dnn_optimizer: Adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 16
    dnn_hidden_units: [64, 32]
    #cin_layer_units: [32, 32]
    hidden_activations: relu
    embedding_dropout: 0
    net_dropout: 0
    batch_norm: False
    epochs: 3
    shuffle: True
    seed: 2022
    #monitor: {'AUC': 1, 'logloss': -1}
    #monitor_mode: 'max'
